# NOTE: The "os" must be specified to work around a library incompatibility in
#       the default one, see:
#         * https://github.com/readthedocs/readthedocs.org/issues/10290

# NOTE: "sphinx-fortran" must be installed manually from GitHub rather than
#       using the release that is currently in PyPy, as the release in PyPy is
#       very old and the GitHub repository has many bug fixes, see:
#         * https://github.com/VACUMM/sphinx-fortran/issues/35
#         * https://github.com/VACUMM/sphinx-fortran/issues/50

version: 2

build:
    apt_packages:
        - gfortran-12
    jobs:
        post_install:
            # As of 27/Sept/2024, the version of Meson available is too old for
            # "f2py" to succeed, see the following error last time I tried:
            #   * meson.build:1:0: ERROR: Meson version is 0.61.2 but project requires >= 1.1.0
            - which f2py
            - which gfortran-12
            - which gmake
            - which meson
            - which pip3
            - which python3
            - pip3 install git+https://github.com/VACUMM/sphinx-fortran.git@master
    os: ubuntu-22.04
    tools:
        python: "3.12"

python:
    install:
        - requirements: docs/requirements.txt
