# NOTE: The "os" must be specified to work around a library incompatibility in
#       the default one, see:
#         * https://github.com/readthedocs/readthedocs.org/issues/10290

version: 2

build:
    jobs:
        post_install:
            - which f2py
            - which pip3
            - which python3
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
        - requirements: docs/requirements.txt
