name: GNU Make

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        steps:
            -
                name: Checkout project                                          # https://github.com/actions/checkout
                uses: actions/checkout@v4
                with:
                    path: main
            -
                name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5                                   # https://github.com/actions/setup-python
                with:
                    python-version: ${{ matrix.python-version }}
            -
                name: Install FORTRAN dependencies
                run: |
                    sudo apt-get install openmpi-bin
                    sudo apt-get install openmpi-common
                    sudo apt-get install libopenmpi-dev
            -
                name: Install Python ${{ matrix.python-version }} dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install matplotlib
                    pip install numpy
                    pip install pylint
                    pip install scipy
                    pip install six
                    pip install sphinx
                    pip install sphinx_rtd_theme
                    pip install git+https://github.com/VACUMM/sphinx-fortran.git@master
            -
                name: Compile the FORTRAN code
                run: |
                    echo "::notice $(which f2py)"
                    echo "::notice $(which gfortran)"
                    echo "::notice $(which gmake)"
                    echo "::notice $(which mpif90)"
                    echo "::notice $(which pip)"
                    echo "::notice $(which python)"
                    cd main
                    gmake -r FC=`which mpif90` PYTHON3=`which python`
