name: GNU Make

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            -
                name: Checkout project                                          # https://github.com/actions/checkout
                uses: actions/checkout@v4
                with:
                    path: main
            -
                name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5                                   # https://github.com/actions/setup-python
                with:
                    python-version: ${{ matrix.python-version }}
            -
                name: Install FORTRAN dependencies
                run: |
                    apt-get install openmpi-bin
            -
                name: Install Python dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install matplotlib
                    pip install pylint
                    pip install scipy
                    pip install sphinx
            -
                name: Compile the FORTRAN code
                run: |
                    echo "::notice $(which gfortran)"
                    echo "::notice $(which gmake)"
                    echo "::notice $(which pip)"
                    echo "::notice $(which python)"
                    cd main
                    gmake -r FC=`which gfortran` PYTHON3=`which python`
